version: '3'
services:

  test-db:
    container_name: test-db
    image: test-db
    build: ./db/
    ports:
      - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  test-sqldef:
    build: ./migrate
    container_name: test-sqldef
    command: --file /sql/schema.sql
    environment:
      WAIT_HOSTS: test-db:3306
      MYSQL_HOST: test-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./migrate/sql:/sql
    links:
      - test-db
volumes:
  test-db-volume: {}
